name: "Create V2"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/480 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php create.php
          php ipv6.php
          git config --global user.email "tonyzhang1995@gmail.com"
          git config --global user.name "zyjia"
          git config credential.helper store
          git add -A
          git commit -m "New server Added ✅ - $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          git push
